name: Build and deploy Node.js app to Azure Web App - QRcodegeneratorPOC

on:
  push:
    branches:
      - qrcode-azure-version
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

      - name: Update npm
        run: npm install -g npm@8.19.4

      - name: npm install and build
        env:
          NPM_CONFIG_LEGACY_PEER_DEPS: true
        run: |
          npm install --legacy-peer-deps
          npm install canvas@2.9.0 --legacy-peer-deps
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BB83C71AF22D47CC9DD13ACB7F3B1E25 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_25B7C4737ACD4345A3F1C0501F2F801B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_415CEDE846A44891B7CAC9BA7526F0CE }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'QRcodegeneratorPOC'
          slot-name: 'Production'
          package: .
